services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: nestjs-api:dev
    env_file:
      - ../.env
    depends_on:
      - database
    ports:
      - '3000:3000'
    volumes:
      - ../:/usr/src/app
    networks:
      - petersblog-network

  database:
    image: postgres:14-alpine
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - petersblog-network

volumes:
  pg-data:

networks:
  petersblog-network:
    driver: bridge
